%include polycode.fmt

%% ── Format directives ────────────────────────────────────────────────────────
%format ->    = "\to"
%format =>    = "\Rightarrow"
%format forall = "\forall"
%format .#.   = "\mathbin{\bullet}"
%format ***   = "\mathbin{\times}"
%format <$>   = "\mathbin{\langle\$\rangle}"
%format @     = "\mathbin{@}"
%% ─────────────────────────────────────────────────────────────────────────────

%if False
\begin{code}
module Declarations where
\end{code}
%endif

\chapter{Declarations}

\section{Generative AI}
I acknowledge the use of Anthropic's Claude Sonnet 4.6 (\url{https://www.claude.ai/}) in the writing of this thesis.
Claude was used for: assistance in drafting the initial testing suite, single-run scripts for visualising training,
assistance in debugging the core implementation of the library and suggestions for improving the phrasing and legibility of the report.

I confirm that no content generated by AI has been presented as my own work without significant
verification and revision, and that I have taken full responsibility for the content of this thesis.

\section{Ethical Considerations}

This project involves no human subjects, animal studies, personal data, or
sensitive information.  All datasets used (Iris, MNIST) are established public
benchmarks with no associated privacy concerns.  The library is released as
open-source software under a permissive licence.  No conflicts of interest
arise from this work.  No formal ethical approval was required or sought.

\section{Sustainability}

All training experiments were conducted on a single CPU-only laptop; no cloud
compute, GPU clusters, or high-performance computing facilities were used.  The
models are intentionally small (1{,}527 parameters for the MNIST CNN) and
training runs completed in minutes to hours rather than days.  A central result
of the thesis is that the typed-lens framework is $5.3\times$ more efficient
than PyTorch's dynamic autograd on the benchmark tasks
(Section~\ref{sec:perf}), which translates directly to reduced energy
consumption for equivalent workloads.  No new hardware was purchased for this
project.